liferay/liferay-screens

android/library/core/src/main/java/com/liferay/mobile/screens/context/LiferayScreensContext.java, android/library/core/src/main/java/com/liferay/mobile/screens/context/LiferayServerContext.java, android/library/core/src/main/res/values/server_context.xml
=> LMW-183 Create Server Context from XML

android/samples/test-app/src/main/res/values/strings.xml
=> Strings formatting

android/README.md, android/documentation/AssetListScreenlet.md, android/documentation/DDLFormScreenlet.md, android/documentation/DDLListScreenlet.md, android/documentation/UserPortraitScreenlet.md, android/documentation/architecture.md, android/documentation/view_creation.md, android/documentation/views.md
Finished editing the docs additions in https://github.com/liferay/liferay-screens/pull/98
=> Wordsmithing new Android docs additions.

README.md
Also renamed 2 sections to reflect their status as overviews of the main usage articles.
=> Table of contents for project readme

android/documentation/view_creation.md, android/library/core/src/main/java/com/liferay/mobile/screens/base/BaseScreenlet.java, android/library/viewsets/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/auth/login/LoginView.java, android/samples/test-app/src/main/AndroidManifest.xml, android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/MainActivity.java, android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/fullview/LoginFullActivity.java, android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/fullview/LoginFullScreenlet.java, android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/fullview/LoginFullView.java, android/samples/test-app/src/main/res/layout/activity_main.xml, android/samples/test-app/src/main/res/layout/login_full.xml, android/samples/test-app/src/main/res/layout/login_full_layout.xml, android/samples/test-app/src/main/res/values/strings.xml
Removing crash if replacing a screenlet with another name and some documentation fixes 
/cc @ngaskill
=> LMW-242 Creating a full view crashes

android/samples/bankofwesteros/src/main/res/values/server_context.xml, android/samples/test-app/src/main/res/layout/asset_list.xml, android/samples/test-app/src/main/res/values/server_context.xml, ios/Samples/Showcase-objc/LiferayScreens-Showcase-Objc/en.lproj/Main.storyboard, ios/Samples/Showcase-objc/LiferayScreens-Showcase-Objc/liferay-server-context.plist, ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift/en.lproj/Main.storyboard, ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift/liferay-server-context.plist, ios/Samples/WesterosBank/App/WesterosBank/ViewControllers/IssuesViewController.xib, ios/Samples/WesterosBank/App/WesterosBank/ViewControllers/ReportIssueViewController.xib, ios/Samples/WesterosBank/App/WesterosBank/liferay-server-context.plist, ios/Samples/WesterosBank/Theme/Auth/UserPortraitScreenlet/UserPortraitView_westeros.swift, ios/Samples/WesterosBank/Theme/DDL/ListScreenlet/DDLListViewCell_westeros.swift
I couldn't test Westeros Bank iOS App (objC & swift samples are OK), I get an unknown symbol in `imageInAnyBundle`, can you find what is missing? seems a problem with the last rebase.
=> LMW-253 Use new portal instance for demo apps

ios/Documentation/theme_creation.md, ios/Documentation/themes.md
I've sent the biggest changes in rewording to Nick, this is just to check if the "concepts" are right (although I have tested them all)
=> LSR-258 Small documentation changes

ios/Framework/Core/Services/LRScreensjournalarticleService_v62.h, ios/Framework/Core/Services/LRScreensjournalarticleService_v62.m, ios/Framework/Core/WebContentDisplayScreenlet/ServerOperations/LiferayWebContentLoadOperation.swift, ios/Framework/Core/WebContentDisplayScreenlet/WebContentDisplayLoadInteractor.swift, ios/Framework/Core/WebContentDisplayScreenlet/WebContentDisplayScreenlet.swift, ios/Framework/LiferayScreens.h, ios/Framework/LiferayScreens.xcodeproj/project.pbxproj
I know it should be in a different interactor :(
=> Feature/LSR-294 iOS

ios/Framework/Core/Auth/LoginScreenlet/LoginScreenlet.swift
=> LSR-705 New method to load stored credentials and fill the values in the LoginScreenlet

android/library/core/src/main/java/com/liferay/mobile/screens/auth/forgotpassword/ForgotPasswordScreenlet.java, android/library/core/src/main/java/com/liferay/mobile/screens/base/BaseScreenlet.java, android/library/core/src/main/java/com/liferay/mobile/screens/base/list/BaseListScreenletView.java, android/library/core/src/main/java/com/liferay/mobile/screens/base/view/BaseViewModel.java, android/library/core/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/assetlist/AssetListView.java, android/library/core/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/auth/forgotpassword/ForgotPasswordView.java, android/library/core/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/auth/login/LoginView.java, android/library/core/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/auth/signup/SignUpView.java, android/library/core/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddl/form/DDLFormView.java, android/library/core/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/userportrait/UserPortraitView.java, android/library/core/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/webcontentdisplay/WebContentDisplayView.java, android/samples/addbookmarkscreenlet/src/main/java/com/liferay/mobile/screens/bookmark/view/AddBookmarkView.java
Way uglier than the iOS version :'(
I don't want to add generics but...
=> LSR-711 Allow the view to see the screenlet

android/library/core/build.gradle, android/library/core/src/main/java/com/liferay/mobile/screens/ddl/XSDParser.java, android/library/core/src/main/java/com/liferay/mobile/screens/ddl/model/Field.java, android/library/core/src/main/java/com/liferay/mobile/screens/ddl/model/NumberField.java, android/library/core/src/main/java/com/liferay/mobile/screens/util/LiferayLocale.java, android/library/core/src/test/java/com/liferay/mobile/screens/auth/login/interactor/LoginInteractorTest.java, android/library/core/src/test/java/com/liferay/mobile/screens/context/SessionContextTest.java, android/library/core/src/test/java/com/liferay/mobile/screens/context/storage/CredentialsStoreSharedPreferencesTest.java, android/library/core/src/test/java/com/liferay/mobile/screens/ddl/XSDParserLocalizationTest.java, android/library/core/src/test/java/com/liferay/mobile/screens/ddl/model/NumberFieldTest.java, android/library/core/src/test/java/com/liferay/mobile/screens/ddl/model/RecordTest.java, android/library/core/src/test/java/com/liferay/mobile/screens/userportrait/UserPortraitInteractorTest.java
=> LSR-293 Fix Android tests

android/library/core/src/main/java/com/liferay/mobile/screens/base/AbstractFactory.java, android/library/core/src/main/java/com/liferay/mobile/screens/base/FactoryCE.java, android/library/core/src/main/java/com/liferay/mobile/screens/base/FactoryProvider.java, android/library/core/src/main/java/com/liferay/mobile/screens/context/LiferayServerContext.java, android/library/core/src/main/java/com/liferay/mobile/screens/context/storage/CredentialsStorageBuilder.java, android/library/core/src/main/java/com/liferay/mobile/screens/context/storage/sharedPreferences/BaseCredentialsStorageSharedPreferences.java, android/library/core/src/main/res/values/list_default_strings.xml, android/library/core/src/main/res/values/server_context.xml, android/library/core/src/main/res/values/strings.xml
=> LSR-651 Use new factory

android/.gitignore, android/build.gradle, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/webcontentdisplay/WebContentDisplayView.java, android/library/src/main/java/com/liferay/mobile/screens/webcontentdisplay/WebContentDisplayListener.java, android/library/src/main/java/com/liferay/mobile/screens/webcontentdisplay/WebContentDisplayScreenlet.java, android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/JournalArticleWithTemplateActivity.java, android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/WebContentDisplayActivity.java
Can't attach a normal onclicklistener due to the webview behaving differently of the other view widgets
=> Listener for onClick events in WebContentScreenlet

android/library/src/main/java/com/liferay/mobile/screens/ddl/model/Field.java
Not for 1.4, requested for a demo.
=> LSR-800 [Android] New Liferay Forms support

ios/Framework/Core/AssetListScreenlet/AssetListPageLoadInteractor.swift, ios/Framework/Core/AssetListScreenlet/AssetListScreenlet.swift, ios/Framework/Core/DDM/DDMJSONParser.swift, ios/Framework/Core/DDM/DDMStructure.swift, ios/Framework/Core/DDM/Fields/DDMFieldDate.swift, ios/Framework/Core/Extensions/Dictionary+Screens.swift, ios/Framework/Core/Extensions/String+Screens.swift, ios/Framework/Core/WebContent/ListScreenlet/WebContentListPageLoadInteractor.swift, ios/Framework/Core/WebContent/ListScreenlet/WebContentListScreenlet.swift, ios/Framework/LiferayScreens.xcodeproj/project.pbxproj, ios/Framework/Tests/Unit/DDM/Fields/DDMFieldBoolean_Tests.swift, ios/Framework/Themes/Default/AssetListScreenlet/AssetListView_default.swift, ios/Framework/Themes/Default/WebContent/ListScreenlet/WebContentListView_default.swift, ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift/BookTheme/WebContentListView_book.swift, ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift/ViewControllers/AssetListScreenletViewController.swift, ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift/ViewControllers/UserPortraitScreenletViewController.swift, ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift/ViewControllers/WebContentListScreenletViewController.swift
Depends on https://github.com/liferay/liferay-screens/pull/266
=> LSR-815 [iOS] List supported entities in AssetList instead of generic assets

ios/Framework/Core/AssetListScreenlet/AssetListScreenlet.swift, ios/Framework/Core/Auth/UserPortraitScreenlet/Interactors/DownloadUserPortraitInteractor.swift, ios/Framework/Core/Base/BaseListScreenlet/BaseListScreenlet.swift, ios/Framework/Core/DDM/Fields/DDMFieldDate.swift, ios/Framework/Core/WebContent/DisplayScreenlet/Connectors/WebContentLoadBaseLiferayConnector.swift, ios/Framework/Core/WebContent/DisplayScreenlet/Connectors/WebContentLoadHtmlLiferayConnector.swift, ios/Framework/Core/WebContent/DisplayScreenlet/Connectors/WebContentLoadStructuredLiferayConnector.swift, ios/Framework/Core/WebContent/DisplayScreenlet/WebContentDisplayLoadInteractor.swift, ios/Framework/Core/WebContent/ListScreenlet/WebContentListScreenlet.swift, ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift/BookTheme/BookTableViewCell.xib, ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift/BookTheme/HtmlTableViewCell.xib, ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift/BookTheme/WebContentListView_book.swift
Depends on https://github.com/liferay/liferay-screens/pull/268
=> LSR-821 [iOS] UserPortraitScreenlet fails loading the image with saved credentials

android/build.gradle, android/library/src/main/AndroidManifest.xml, android/library/src/main/java/com/liferay/mobile/screens/push/PushScreensActivity.java, android/samples/pushnotifications/src/main/AndroidManifest.xml, android/samples/pushnotifications/src/main/java/com/liferay/mobile/pushnotifications/activities/NotificationDetailActivity.java, android/samples/pushnotifications/src/main/res/layout/ddl_list_item_push.xml, android/samples/pushnotifications/src/main/res/values/server_context.xml, android/samples/pushnotifications/src/main/res/values/strings.xml
Ready, I'm going to integrate to release it with 1.4
=> LSR-841 Update Push Application

android/library/src/main/java/com/liferay/mobile/screens/base/BaseScreenlet.java
Reverts liferay/liferay-screens#279
=> Revert "LSR-852 add showStartOperation to onUserAction in BaseScreenlet"

android/library/src/main/java/com/liferay/mobile/screens/assetlist/AssetListScreenlet.java, android/library/src/main/java/com/liferay/mobile/screens/auth/forgotpassword/ForgotPasswordScreenlet.java, android/library/src/main/java/com/liferay/mobile/screens/auth/login/LoginScreenlet.java, android/library/src/main/java/com/liferay/mobile/screens/auth/signup/SignUpScreenlet.java, android/library/src/main/java/com/liferay/mobile/screens/base/BaseScreenlet.java, android/library/src/main/java/com/liferay/mobile/screens/base/list/BaseListScreenlet.java, android/library/src/main/java/com/liferay/mobile/screens/ddl/form/DDLFormScreenlet.java, android/library/src/main/java/com/liferay/mobile/screens/ddl/list/DDLListScreenlet.java, android/library/src/main/java/com/liferay/mobile/screens/userportrait/UserPortraitScreenlet.java, android/library/src/main/java/com/liferay/mobile/screens/webcontent/display/WebContentDisplayScreenlet.java, android/library/src/main/java/com/liferay/mobile/screens/webcontent/list/WebContentListScreenlet.java, android/samples/addbookmarkscreenlet/src/main/java/com/liferay/mobile/screens/bookmark/AddBookmarkScreenlet.java, android/samples/listbookmarkscreenlet/src/main/java/com/liferay/mobile/screens/listbookmark/BookmarkListScreenlet.java, android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/fullview/LoginFullScreenlet.java, android/viewsets/westeros/src/main/java/com/liferay/mobile/screens/viewsets/westeros/auth/signup/SignUpScreenlet.java
This would be how it would be used:
```
UserPortraitScreenlet userPortraitScreenlet = new UserPortraitScreenlet(getContext());
userPortraitScreenlet.setLayoutParams(new LayoutParams(getLayoutParams().width, getLayoutParams().height));
userPortraitScreenlet.setAutoLoad(true);
userPortraitScreenlet.setOfflinePolicy(OfflinePolicy.REMOTE_FIRST);
userPortraitScreenlet.setUserId(20199);
userPortraitScreenlet.render(R.layout.userportrait_default);
```
@dgarciasarai
=> LSR-862 Allow on demand rendering of the screenlet view

ios/Framework/Core/Base/BaseScreenlet.swift, ios/Framework/Core/Base/BaseScreenletView.swift, ios/Framework/Core/Base/MBProgressHUDPresenter.swift, ios/Framework/Core/Base/ProgressPresenter.swift, ios/Framework/Core/DDL/FormScreenlet/DDLFormScreenlet.swift, ios/Framework/Themes/Default/Auth/UserPortraitScreenlet/UserPortraitDefaultProgressPresenter.swift, ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift.xcodeproj/project.pbxproj, ios/Samples/Showcase-swift/Podfile.lock
This new aproach will allow developers to modify the type of progress shown for each interactor-state.
=> LSR-873 Improve progress presenters architecture

android/samples/westerosemployees/src/main/java/com/liferay/mobile/screens/westerosemployees/Views/SignUpCard.java, android/samples/westerosemployees/src/main/java/com/liferay/mobile/screens/westerosemployees/activities/MainActivity.java, android/samples/westerosemployees/src/main/java/com/liferay/mobile/screens/westerosemployees/activities/SplashActivity.java, android/samples/westerosemployees/src/main/java/com/liferay/mobile/screens/westerosemployees/activities/UserProfileActivity.java, android/samples/westerosemployees/src/main/res/layout/main.xml
- store/destroy credentials
- include cache sync
=> LSR-912 improvements to Android Westeros Employees APP

android/library/src/main/java/com/liferay/mobile/screens/auth/login/LoginScreenlet.java, android/library/src/main/java/com/liferay/mobile/screens/context/storage/CredentialsStorageBuilder.java, android/library/src/test/java/com/liferay/mobile/screens/context/storage/CredentialsStoreBuilderTest.java
* Don't store credentials when StorageType is NONE.
* Remove store credentials before store the new ones.
=> LSR-926 Fix bugs with LoginScreenlet (Android)

ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift.xcodeproj/project.pbxproj, ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift/ViewControllers/Files/AudioDisplayViewController.swift, ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift/ViewControllers/Files/PdfDisplayViewController.swift, ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift/ViewControllers/Files/VideoDisplayViewController.swift, ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift/ViewControllers/HomeScreenletsViewController.swift, ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift/en.lproj/AudioDisplayScreenlet.storyboard, ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift/en.lproj/PdfDisplayScreenlet.storyboard, ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift/en.lproj/VideoDisplayScreenlet.storyboard, ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift/liferay-server-context.plist
Created examples for:
- AudioDisplayScreenlet
- VideoDisplayScreenlet
- PdfDisplayScreenlet
=> LSR-929 Add file examples to Showcase-Swift

android/library/src/main/java/com/liferay/mobile/screens/dlfile/display/pdf/OnSwipeTouchListener.java, android/library/src/main/java/com/liferay/mobile/screens/dlfile/display/pdf/SwipeListener.java, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/dlfile/display/PdfDisplayView.java, android/library/src/main/res/layout/pdf_display_default.xml, android/library/src/main/res/values/pdf_display_default_strings.xml
* Fixed bug with buttons: they appear now when the device is in portrait and landscape mode.
* Added swipe left and swipe right to move into pages.
=> LSR-928 Improvements to PdfDisplayScreenlet (Android)

ios/Framework/Core/Base/BaseListScreenlet/CollectionView/BaseListCollectionView.swift, ios/Framework/Core/Base/BaseListScreenlet/TableView/BaseListTableView.swift
With this change user will have access to tableView/CollectionView.indexPathForSelectedRow
=> LSR-892 Deselect row after delegate call

android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/webcontent/list/WebContentListAdapter.java, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/webcontent/list/WebContentListView.java, android/library/src/main/res/layout/ddlfield_checkbox_default.xml, android/library/src/main/res/layout/ddlfield_date_default.xml, android/library/src/main/res/layout/ddlfield_document_default.xml, android/library/src/main/res/layout/ddlfield_number_default.xml, android/library/src/main/res/layout/ddlfield_radio_default.xml, android/library/src/main/res/layout/ddlfield_select_default.xml, android/library/src/main/res/layout/ddlfield_text_area_default.xml, android/library/src/main/res/layout/ddlfield_text_default.xml, android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/FilteredAssetActivity.java, android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/WebContentDisplayActivity.java, android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/WebContentListActivity.java, android/samples/test-app/src/main/res/layout/web_content_display_list.xml
Fixed examples:
- WebContentList
- Filtered Asset
- DDLForm
=> LSR-938 Test-app Improvements

android/library/src/main/java/com/liferay/mobile/screens/asset/list/interactor/AssetListInteractor.java, android/library/src/main/java/com/liferay/mobile/screens/context/User.java, android/library/src/main/res/values/strings.xml, android/library/src/test/java/com/liferay/mobile/screens/context/SessionContextTest.java, android/library/src/test/java/com/liferay/mobile/screens/context/storage/CredentialsStoreSharedPreferencesTest.java, android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/AssetListActivity.java, android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/utils/AssetClassnameIds70.java, android/samples/test-app/src/main/res/values/server_context.xml, ios/Framework/Core/Asset/ListScreenlet/AssetListPageLiferayConnector.swift, ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift/en.lproj/AssetListScreenlet.storyboard
AssetListScreenlet can't list assets which type is "User" because by default uses the attribute _visible_ to _true_ and in this case, it needs to be set to _false_.
=> LSR-930 List users with AssetListScreenlet

CHANGELOG.md, android/build.gradle, android/library/src/main/java/com/liferay/mobile/screens/userportrait/UserPortraitScreenlet.java, android/library/src/main/java/com/liferay/mobile/screens/userportrait/interactor/UserPortraitInteractorListener.java, android/library/src/main/java/com/liferay/mobile/screens/userportrait/interactor/load/UserPortraitLoadInteractor.java, android/library/src/main/java/com/liferay/mobile/screens/userportrait/view/UserPortraitViewModel.java, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/userportrait/UserPortraitView.java, android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/customviews/UserPortraitInitialsView.java, android/samples/test-app/src/main/res/drawable/rounded_corner.xml, android/samples/test-app/src/main/res/layout/user_portrait.xml, android/samples/test-app/src/main/res/layout/userportrait_initials.xml, ios/Framework/Core/Auth/UserPortraitScreenlet/Interactors/DownloadUserPortraitInteractor.swift, ios/Framework/Core/Auth/UserPortraitScreenlet/UserPortraitScreenlet.swift, ios/Framework/Core/Auth/UserPortraitScreenlet/UserPortraitViewModel.swift, ios/Framework/Themes/Default/Auth/UserPortraitScreenlet/UserPortraitView_default.swift, ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift.xcodeproj/project.pbxproj, ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift/CustomViews/UserPortraitView_initials.swift, ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift/CustomViews/UserPortraitView_initials.xib, ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift/ViewControllers/Others/UserPortraitScreenletViewController.swift, ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift/en.lproj/UserPortraitScreenlet.storyboard
Right now all the user information is being saved into cache but I think that not all is needed
What do you think could be the interesting information for rendering the placeholder? 
Maybe with the user name, surname and email will be enough?
@dgarciasarai @jmnavarro @nhpatt
=> LSR-985 Custom placeholder with user info

CHANGELOG.md, ios/Framework/Core/Auth/UserPortraitScreenlet/UserPortraitScreenlet.swift, ios/Framework/Core/Auth/UserPortraitScreenlet/UserPortraitViewModel.swift, ios/Framework/Themes/Default/Auth/UserPortraitScreenlet/UserPortraitView_default.swift, ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift/CustomViews/UserPortraitView_initials.swift, ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift/ViewControllers/Others/UserPortraitScreenletViewController.swift, ios/Samples/Showcase-swift/Podfile.lock
Extract methods, add missing comments, add marks and SF
=> LSR-1002 Refactor UserPortraitScreenlet

CHANGELOG.md, android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/customviews/UserPortraitInitialsView.java, android/samples/test-app/src/main/res/drawable/rounded_corner.xml, android/samples/test-app/src/main/res/layout/userportrait_initials.xml
The initials view background was always on top.
=> LSR-990 Image doesn't show correctly in UserPortraitScreenlet with user initials view

CHANGELOG.md, xamarin/Framework/LiferayScreens.Android/Additions/UserPortrait/UserPortraitScreenlet.cs, xamarin/Framework/LiferayScreens.Android/LiferayScreens_Android.csproj, xamarin/Framework/LiferayScreens.Android/Transforms/Metadata.xml, xamarin/Framework/LiferayScreens.iOS/LiferayScreens_iOS.csproj, xamarin/Framework/LiferayScreens.iOS/Models/User.cs, xamarin/Framework/LiferayScreens.iOS/UserPortrait/UserPortraitScreenlet.cs, xamarin/Framework/LiferayScreens.iOS/UserPortrait/UserPortraitScreenletDelegate.cs, xamarin/Framework/LiferayScreens.iOS/UserPortrait/UserPortraitViewModel.cs, xamarin/Framework/LiferayScreens.nuspec
=> LSR-1040 Liferay Screens Xamarin: UserPortraitScreenlet binding

.travis.yml, CHANGELOG.md, LiferayScreens.podspec, ios/Framework/Core/Base/Interactor.swift, ios/Framework/Podfile.lock, ios/Samples/AndorraTelecomPublic/Podfile.lock, ios/Samples/Showcase-ObjectiveC/LiferayScreens-Showcase-ObjectiveC.xcodeproj/project.pbxproj, ios/Samples/Showcase-ObjectiveC/Podfile.lock, ios/Samples/Showcase-swift/Podfile.lock, ios/Samples/WesterosBank/App/Podfile.lock, ios/Samples/WesterosBank/App/WesterosBank.xcodeproj/project.pbxproj, ios/Samples/WesterosEmployees-hybrid/App/Podfile.lock, ios/Samples/WesterosEmployees/App/Podfile.lock, ios/Samples/WesterosEmployees/App/WesterosEmployees.xcodeproj/project.pbxproj
We are still missing the migration to Swift 4
=> Update xcode 9 (Swift 3.2)

CHANGELOG.md, android/library/src/main/AndroidManifest.xml, android/library/src/main/java/com/liferay/mobile/screens/base/ScreensFileProvider.java
More info about the problem here: https://commonsware.com/blog/2017/06/27/fileprovider-libraries.html
=> LSR-1055 Allow users to define their own fileprovider

CHANGELOG.md, android/library/src/main/java/com/liferay/mobile/screens/util/AssetReader.java, android/library/src/main/java/com/liferay/mobile/screens/util/ScriptReader.java, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/web/ScreensNativeWebView.java, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/web/cordova/ScreensCordovaWebView.java, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/web/cordova/ScreensCordovaWebViewClient.java, android/library/src/main/java/com/liferay/mobile/screens/web/WebScreenlet.java, android/library/src/main/java/com/liferay/mobile/screens/web/WebScreenletConfiguration.java, android/library/src/main/java/com/liferay/mobile/screens/webcontent/display/WebContentDisplayScreenlet.java, android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/WebActivity.java
This PR fix this problems
- Fix ssl errors
- Remove comments in files allowing developers to use //coments in the js code.
=> Feedback webscreenlet

android/library/src/test/java/com/liferay/mobile/screens/userportrait/UserPortraitInteractorTest.java
//because victor is too smart for my taste
=> Fix travis

android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties, android/library/src/main/java/com/liferay/mobile/screens/webcontent/WebContent.java, android/samples/test-app/src/main/res/values/server_context.xml, xamarin/Framework/LiferayAndroidSdk.BindingLibrary/LiferayAndroidSdk.BindingLibrary.csproj, xamarin/Framework/LiferayScreens.Android/Additions/Ddl/Form/Model/GeolocationField.cs, xamarin/Framework/LiferayScreens.Android/Additions/Viewset/Default/DDL/Form/DDLFieldGeoView.cs, xamarin/Framework/LiferayScreens.Android/LiferayScreens_Android.csproj, xamarin/Framework/LiferayScreens.Android/Transforms/Metadata.xml, xamarin/Framework/LiferayScreens.nuspec, xamarin/Framework/LiferayScreens.sln, xamarin/Framework/OkHttp.BindingLibrary/OkHttp.BindingLibrary.csproj, xamarin/Framework/OkHttp.BindingLibrary/Properties/AssemblyInfo.cs, xamarin/Framework/OkHttp.BindingLibrary/Transforms/EnumFields.xml, xamarin/Framework/OkHttp.BindingLibrary/Transforms/EnumMethods.xml, xamarin/Framework/OkHttp.BindingLibrary/Transforms/Metadata.xml, xamarin/Samples/Showcase-Android/Activities/CommentListActivity.cs, xamarin/Samples/Showcase-Android/Activities/ImageGalleryActivity.cs, xamarin/Samples/Showcase-Android/Resources/Resource.designer.cs, xamarin/Samples/Showcase-Android/Resources/layout/AssetListView.axml, xamarin/Samples/Showcase-Android/Resources/layout/WebContentDisplayView.axml, xamarin/Samples/Showcase-Android/Resources/values/server_context.xml, xamarin/Samples/Showcase-Android/Showcase-Android.csproj, xamarin/Samples/Showcase-Android/packages.config, xamarin/Samples/Showcase-iOS/Showcase-iOS.csproj, xamarin/Samples/Showcase-iOS/packages.config
Final changes for Liferay Screens 1.0.0 for Xamarin release:
* Update values for test server
* Ignore full parsing if structure is missing in WebContent
* Create OkHttp binding library and link it in LiferayAndroidSdk binding library
* Configure for LiferayScreens and the sample projects (Showcase-Android and Showcase-iOS) in the same project
=> LSR-1088 Xamarin.Android final changes

CHANGELOG.md, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/webcontent/display/WebContentDisplayView.java, android/samples/test-app/src/main/res/values-es/strings.xml
Link's content was shown as text
=> LPP-28893 Fixed error when we navigate inside WebContentDisplayScreenlet

CHANGELOG.md, ios/Framework/Core/WebContent/DisplayScreenlet/WebContentDisplayScreenlet.swift, ios/Framework/Core/WebContent/DisplayScreenlet/WebContentDisplayViewModel.swift, ios/Framework/Themes/Default/WebContent/DisplayScreenlet/WebContentDisplayView_default.swift, ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift/BookTheme/WebContentDisplayView_book.swift, ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift/ViewControllers/WebContent/WebContentDisplayScreenletViewController.swift
=> LSR-1094 Create new delegate in WebContentDisplayScreenlet to allow or not navigation inside the WKWebView (changes)

ios/Framework/Core/Auth/SignUpScreenlet/SignUpScreenlet.swift, ios/Framework/Core/Auth/UserPortraitScreenlet/UserPortraitScreenlet.swift, ios/Framework/Tests/theme-test/LoginView_test.xib, ios/Framework/Themes/Default/Auth/ForgotPasswordScreenlet/ForgotPasswordView_default.swift, ios/Framework/Themes/Default/Auth/ForgotPasswordScreenlet/ForgotPasswordView_default.xib, ios/Framework/Themes/Default/Auth/LoginScreenlet/LoginView_default.swift, ios/Framework/Themes/Default/Auth/LoginScreenlet/LoginView_default.xib, ios/Framework/Themes/Default/Auth/SignUpScreenlet/SignUpView_default.swift, ios/Framework/Themes/Default/Auth/SignUpScreenlet/SignUpView_default.xib, ios/Framework/Themes/Default/Auth/UserPortraitScreenlet/UserPortraitView_default.swift, ios/Framework/Themes/Default/Auth/UserPortraitScreenlet/UserPortraitView_default.xib, ios/Framework/Themes/Default/Comment/Add/CommentAddView_default.xib, ios/Framework/Themes/Default/Comment/Display/CommentEditViewController_default.xib, ios/Framework/Themes/Default/DDL/FormScreenlet/DDLFieldDocumentlibraryPresenterViewController_default.xib, ios/Framework/Themes/Default/DDL/FormScreenlet/DDLSubmitButtonTableCell_default.xib, ios/Framework/Themes/Default/Rating/RatingView_default-emojis.swift, ios/Framework/Themes/Default/Rating/RatingView_default-like.swift, ios/Framework/Themes/Default/Rating/RatingView_default-thumbs.swift, ios/Framework/Themes/Default/Rating/RatingView_default-thumbs.xib, ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift/ViewControllers/Others/UserPortraitScreenletViewController.swift
Removed unnecessary `restorationIdentifier` properties from code.
This PR complements #528.
No CHANGELOG changes made.
=> LSR-1079 Remove trigger action with identifier and UITextFieldDelegate in BaseScreenletView (final changes)

CHANGELOG.md, android/library/src/main/java/com/liferay/mobile/screens/cache/Cache.java, android/library/src/main/java/com/liferay/mobile/screens/cache/PendingItemsToSyncListener.java, android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/MainActivity.java, android/samples/test-app/src/main/res/values-es/info_strings.xml, android/samples/test-app/src/main/res/values/info_strings.xml, ios/Framework/Core/Offline/SyncManager.swift
As a developer, I want to know if there are pending items ready to be synchronized before calling `resync()` (Android) or `startSync()` (iOS).
=> LSR-1084 Add a new method to the sync service to know if there are items to synchronize

CHANGELOG.md, android/build.gradle, android/library/src/main/java/com/liferay/mobile/screens/auth/login/LoginRedirectListener.java, android/library/src/main/java/com/liferay/mobile/screens/auth/login/LoginScreenlet.java, android/library/src/main/java/com/liferay/mobile/screens/auth/login/interactor/LoginCookieInteractor.java, android/library/src/main/java/com/liferay/mobile/screens/auth/login/interactor/LoginOAuth2RedirectInteractor.java, android/library/src/main/java/com/liferay/mobile/screens/auth/login/interactor/LoginOAuth2ResumeRedirectInteractor.java, android/library/src/main/java/com/liferay/mobile/screens/auth/login/interactor/LoginOAuth2UsernameAndPasswordInteractor.java, android/library/src/main/java/com/liferay/mobile/screens/base/AbstractFactory.java, android/library/src/main/java/com/liferay/mobile/screens/base/FactoryCE.java, android/library/src/main/java/com/liferay/mobile/screens/context/AuthenticationType.java, android/library/src/main/java/com/liferay/mobile/screens/context/SessionContext.java, android/library/src/main/java/com/liferay/mobile/screens/context/storage/CredentialsStorageBuilder.java, android/library/src/main/java/com/liferay/mobile/screens/context/storage/sharedPreferences/OAuth2CredentialsStorageSharedPreferences.java, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/auth/login/LoginView.java, android/library/src/main/res/layout/login_default.xml, android/library/src/main/res/values/attrs.xml, android/library/src/test/java/com/liferay/mobile/screens/context/storage/CredentialsStoreSharedPreferencesTest.java, android/samples/bankofwesteros/src/main/java/com/liferay/mobile/screens/bankofwesteros/activities/MainActivity.java, android/samples/pushnotifications/src/main/java/com/liferay/mobile/pushnotifications/activities/LoginActivity.java, android/samples/test-app/src/main/AndroidManifest.xml, android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/CustomInteractorActivity.java, android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/LoginActivity.java, android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/ReloginActivity.java, android/samples/test-app/src/main/res/layout/login.xml, android/samples/test-app/src/main/res/values/server_context.xml, android/samples/test-app/src/main/res/values/strings.xml, android/samples/westerosemployees-hybrid/src/main/java/com/liferay/mobile/screens/westerosemployees_hybrid/activities/MainActivity.java, android/samples/westerosemployees/src/main/java/com/liferay/mobile/screens/westerosemployees/activities/MainActivity.java
I would like to hear your thought about the new void `onAuthenticationBrowserShown();` method on LoginListener
=> LSR-1107 OAuth2 Authentication Android

ios/Framework/Core/Extensions/SequenceType+Screens.swift, ios/Framework/LiferayScreens.xcodeproj/project.pbxproj, ios/Framework/LiferayScreens.xcodeproj/xcshareddata/xcschemes/LiferayScreens.xcscheme, ios/Framework/Themes/Default/Portlet/cordova/ScreensCordovaWebView.swift, ios/Framework/Themes/Default/Rating/RatingView_default-emojis.swift, ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift.xcodeproj/project.pbxproj, ios/Samples/Showcase-swift/LiferayScreens-Showcase-Swift/en.lproj/Main.storyboard, ios/Samples/Showcase-swift/Podfile.lock
* Update pods
* Update Main storyboard: move sign up button inside login view
* Change `flatMap` to `compactMap` to avoid warnings
=> #trivial Avoid warnings and update Main storyboard

android/library/src/main/java/com/liferay/mobile/screens/thingscreenlet/model/BlogPosting.kt, android/library/src/main/java/com/liferay/mobile/screens/thingscreenlet/model/Collection.kt, android/library/src/main/java/com/liferay/mobile/screens/thingscreenlet/model/Comment.kt, android/library/src/main/java/com/liferay/mobile/screens/thingscreenlet/model/WorkflowTask.kt, android/library/src/main/java/com/liferay/mobile/screens/thingscreenlet/screens/adapter/ThingAdapter.kt, android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/postings/activity/DetailActivity.kt, android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/postings/activity/EditActivity.kt, android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/postings/activity/ThingMainActivity.kt, android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/postings/view/BlogPostingDetailCustom.kt, android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/postings/view/CollectionDetailCustomView.kt
=> #trivial Fix Android Studio project

CHANGELOG.md, android/library/src/main/java/com/liferay/mobile/screens/ddl/model/DDMStructure.java, android/library/src/main/java/com/liferay/mobile/screens/ddl/model/Field.java, android/library/src/main/java/com/liferay/mobile/screens/ddm/form/model/CheckboxMultipleField.java, android/library/src/main/java/com/liferay/mobile/screens/ddm/form/model/FieldValue.kt, android/library/src/main/java/com/liferay/mobile/screens/ddm/form/model/FormContext.kt, android/library/src/main/java/com/liferay/mobile/screens/ddm/form/model/FormInstance.kt, android/library/src/main/java/com/liferay/mobile/screens/ddm/form/model/FormInstanceRecord.kt, android/library/src/main/java/com/liferay/mobile/screens/ddm/form/model/FormPage.kt, android/library/src/main/java/com/liferay/mobile/screens/ddm/form/model/Grid.kt, android/library/src/main/java/com/liferay/mobile/screens/ddm/form/model/GridField.kt, android/library/src/main/java/com/liferay/mobile/screens/ddm/form/model/RepeatableField.kt, android/library/src/main/java/com/liferay/mobile/screens/ddm/form/model/SuccessPage.kt
Guys, this is part of our forms screenlet, I'll split in some PRs to avoid tons of files to review.
@dgarciasarai @victorg1991 @nhpatt
=> LPS-86352 Support Checkbox Multiple, Grid and Repeatable fields on Field model

CHANGELOG.md, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/dlfile/display/PdfDisplayView.java
=> LPS-87438 Create onPageRendered method on PdfDisplayView

android/library/src/main/java/com/liferay/mobile/screens/ddl/form/util/FormFieldKeys.kt, android/library/src/main/java/com/liferay/mobile/screens/ddl/model/Field.java
=> #trivial MOBILE-1026 Fix placeholder key on Field creation

android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/fields/DDMFieldRepeatableView.kt
=> #trivial MOBILE-1028 Fix request focus when a repeatable item is removed

android/library/src/main/java/com/liferay/mobile/screens/thingscreenlet/screens/ThingScreenlet.kt, android/library/src/main/java/com/liferay/mobile/screens/thingscreenlet/screens/views/Scenarios.kt, android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/postings/activity/ThingMainActivity.kt
=> #trivial MOBILE-1001 Parcelable implementation for Scenarios

android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/DDMFormView.kt
=> #trivial MOBILE-1051 Reduce debounce timeout for autosave and evaluate context

android/library/src/main/java/com/liferay/mobile/screens/ddl/model/DateField.java
=> #trivial MOBILE-966 DateField refactor

android/library/src/main/java/com/liferay/mobile/screens/util/LiferayLogger.java, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddl/form/fields/BaseDDLFieldTextView.java, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddl/form/fields/DDLDocumentFieldView.java, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/DDMFormView.kt
=> #trivial MOBILE-1055 Add upload callbacks to update field state and emit onChange events

android/library/src/main/java/com/liferay/mobile/screens/ddl/exception/EmptyDocumentRemoteFileException.kt, android/library/src/main/java/com/liferay/mobile/screens/ddl/model/DocumentField.java, android/library/src/main/java/com/liferay/mobile/screens/ddl/model/DocumentRemoteFile.java, android/library/src/test/java/com/liferay/mobile/screens/ddl/model/DocumentFieldTest.java
=> #trivial MOBILE-967 Fix empty json value into DocumentField

CHANGELOG.md, android/build.gradle, android/library/src/main/java/com/liferay/mobile/screens/context/SessionContext.java, android/library/src/main/java/com/liferay/mobile/screens/ddm/form/DDMFormListener.kt, android/library/src/main/java/com/liferay/mobile/screens/ddm/form/service/APIOEvaluateService.kt, android/library/src/main/java/com/liferay/mobile/screens/ddm/form/service/APIOFetchLatestDraftService.kt, android/library/src/main/java/com/liferay/mobile/screens/ddm/form/service/APIOSubmitService.kt, android/library/src/main/java/com/liferay/mobile/screens/ddm/form/service/APIOUploadService.kt, android/library/src/main/java/com/liferay/mobile/screens/ddm/form/service/BaseAPIOService.kt, android/library/src/main/java/com/liferay/mobile/screens/thingscreenlet/screens/ThingScreenlet.kt, android/library/src/main/java/com/liferay/mobile/screens/thingscreenlet/screens/adapter/ThingAdapter.kt, android/library/src/main/java/com/liferay/mobile/screens/util/ServiceUtil.kt, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddl/form/fields/DDLDocumentFieldView.java, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/DDMFormContract.kt, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/DDMFormInteractor.kt, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/DDMFormPresenter.kt, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/DDMFormView.kt, android/liferay-services-integration/build.gradle, android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/DDMFormActivity.java, android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/postings/activity/DetailActivity.kt, android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/postings/activity/ThingMainActivity.kt, android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/workflow/activity/WorkflowListActivity.kt
@victorg1991 @dgarciasarai I closed the previous PR just to keep it simple and avoid tons of non-related changes in the PR. Please review when you can. Thanks!
=> MOBILE-1081 Add support for form translations

android/library/src/main/java/com/liferay/mobile/screens/util/StringUtils.kt, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddl/form/fields/BaseDDLFieldTextView.java, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddl/form/fields/DDLFieldRadioView.java, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/fields/DDMFieldCheckboxMultipleView.java, android/library/src/main/res/layout/ddlfield_checkbox_default.xml, android/library/src/main/res/layout/ddlfield_date_default.xml, android/library/src/main/res/layout/ddlfield_document_default.xml, android/library/src/main/res/layout/ddlfield_number_default.xml, android/library/src/main/res/layout/ddlfield_radio_default.xml, android/library/src/main/res/layout/ddlfield_select_default.xml, android/library/src/main/res/layout/ddlfield_text_area_default.xml, android/library/src/main/res/layout/ddlfield_text_default.xml, android/library/src/main/res/layout/ddmfield_checkbox_multiple_default.xml, android/library/src/main/res/values/dimens.xml, android/viewsets/lexicon/src/main/res/layout/ddlfield_date_lexicon.xml, android/viewsets/lexicon/src/main/res/layout/ddlfield_document_lexicon.xml, android/viewsets/lexicon/src/main/res/layout/ddlfield_number_lexicon.xml, android/viewsets/lexicon/src/main/res/layout/ddlfield_radio_lexicon.xml, android/viewsets/lexicon/src/main/res/layout/ddlfield_select_dialog_lexicon.xml, android/viewsets/lexicon/src/main/res/layout/ddlfield_select_lexicon.xml, android/viewsets/lexicon/src/main/res/layout/ddlfield_text_area_lexicon.xml, android/viewsets/lexicon/src/main/res/layout/ddlfield_text_lexicon.xml, android/viewsets/lexicon/src/main/res/layout/ddmfield_checkbox_multiple_lexicon.xml, android/viewsets/lexicon/src/main/res/layout/ddmfield_grid_lexicon.xml, android/viewsets/lexicon/src/main/res/values/colors_lexicon.xml
=> #trivial MOBILE-1027 Render Help Text on all needed fields

android/library/src/main/java/com/liferay/mobile/screens/ddl/form/util/FormConstants.kt, android/library/src/main/java/com/liferay/mobile/screens/ddm/form/DDMFormScreenlet.kt, android/library/src/main/java/com/liferay/mobile/screens/ddm/form/service/APIOGetFormService.kt, android/library/src/main/java/com/liferay/mobile/screens/util/AndroidExtensions.kt, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/DDMFormContract.kt, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/DDMFormPresenter.kt, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/DDMFormView.kt, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/DDMFormViewConfig.kt, android/library/src/main/res/values/attrs.xml
@victorg1991 @dgarciasarai could you review it? Thanks (:
=> #trivial MOBILE-1088 Add config parameters on DDMFormScreenlet

android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddl/form/fields/DDLFieldSelectView.java, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/fields/DDMFieldGridRowView.kt, android/library/src/main/res/values/strings.xml, android/viewsets/lexicon/src/main/java/com/liferay/mobile/screens/viewsets/lexicon/ddl/form/fields/DDLFieldSelectView.java
Guys, could you review this one? Thanks! @victorg1991 @dgarciasarai
=> #trivial MOBILE-1091 Add clear option on Select and Grid dialogs

android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/DDMFormContract.kt, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/DDMFormPresenter.kt, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/DDMFormView.kt
Guys, could you review? Thanks (:
=> #trivial MOBILE-1050 Reset record state after submit

android/library/src/main/java/com/liferay/mobile/screens/ddm/form/DDMFormListener.kt, android/library/src/main/java/com/liferay/mobile/screens/ddm/form/DDMFormScreenlet.kt, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/events/FormEvents.kt, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/DDMFormContract.kt, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/DDMFormPresenter.kt, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/DDMFormView.kt, android/samples/test-app/src/main/java/com/liferay/mobile/screens/testapp/DDMFormActivity.java, android/samples/test-app/src/main/res/values/info_strings.xml
=> #trivial MOBILE-1089 Add form submitted, draft saved and record loaded events

android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/DDMFormContract.kt, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/DDMFormPresenter.kt, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/DDMFormView.kt
=> #trivial MOBILE-1089 Change DDMFormListener to be optional

android/library/src/main/java/com/liferay/mobile/screens/ddl/NumberValidator.kt, android/library/src/main/java/com/liferay/mobile/screens/ddl/StringValidator.kt, android/library/src/main/java/com/liferay/mobile/screens/ddl/Validation.kt, android/library/src/main/java/com/liferay/mobile/screens/ddl/model/NumberField.java, android/library/src/test/java/com/liferay/mobile/screens/ddm/NumberValidatorTest.java, android/library/src/test/java/com/liferay/mobile/screens/ddm/StringValidatorTest.java
Guys, just formatting some old codes that were missed previously.
=> Run detekt format

android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddl/form/fields/BaseDDLFieldTextView.java, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddl/form/fields/DDLDocumentFieldView.java, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddl/form/fields/DDLFieldRadioView.java, android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/fields/DDMFieldCheckboxMultipleView.java
Guys, could you review this PR? Thanks!
@dgarciasarai @victorg1991 @victorlaerte
=> #trivial MOBILE-1118 Skip first field change emission to avoid wrong dirty fields

android/library/src/main/java/com/liferay/mobile/screens/viewsets/defaultviews/ddm/form/DDMFormPresenter.kt
Guys, I'll send some PRs but the idea is just to merge after the @victorlaerte PR because it is being developed above the `develop-hypermedia` tag. Probably we'll have some conflicts that I'll have to resolve here.
cc @victorg1991 @dgarciasarai
=> #trivial MOBILE-1119 Restore reset state and set value only evaluate changed it
